# Docker Compose used with Spring Compose feature
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=insurance-app-db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=insurance-app-db-user'
    ports:
      - '15432:5432'
