services:
  frontend:
    image: insurance-app-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    image: insurance-app:latest
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/insurance-app-prod-db
      - spring.datasource.username=insurance-app-prod-db-user
      - spring.datasource.password=secret
    ports:
      - "8090:8080"

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=insurance-app-prod-db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=insurance-app-prod-db-user'
